import XCTest
@testable import MTKCore

final class AdvancedToneCurveModelTests: XCTestCase {
    func testSettingControlPointsSanitizesOrderingAndBounds() {
        let model = AdvancedToneCurveModel()
        let chaoticPoints: [AdvancedToneCurvePoint] = [
            .init(x: 220, y: 0.4),
            .init(x: -32, y: -0.5),
            .init(x: 80, y: 0.2),
            .init(x: 300, y: 1.5)
        ]

        model.setControlPoints(chaoticPoints)
        let sanitized = model.currentControlPoints()

        guard let first = sanitized.first, let last = sanitized.last else {
            return XCTFail("Expected sanitized control points to include endpoints")
        }
        XCTAssertEqual(first.x, AdvancedToneCurveModel.xRange.lowerBound, accuracy: 0.001)
        XCTAssertEqual(last.x, AdvancedToneCurveModel.xRange.upperBound, accuracy: 0.001)
        XCTAssertEqual(first.y, AdvancedToneCurveModel.yRange.lowerBound, accuracy: 0.001)
        XCTAssertEqual(last.y, AdvancedToneCurveModel.yRange.upperBound, accuracy: 0.001)

        for index in 1..<sanitized.count {
            XCTAssertGreaterThan(sanitized[index].x, sanitized[index - 1].x, "Control points must remain strictly increasing on the X axis")
        }
    }

    func testAutoWindowPresetProducesCurveAlignedWithHistogram() {
        var histogram = [UInt32](repeating: 0, count: 256)
        for index in 40...120 {
            histogram[index] = 5_000
        }

        let model = AdvancedToneCurveModel()
        XCTAssertEqual(model.currentControlPoints().count, AdvancedToneCurveModel.defaultControlPoints().count)

        model.setHistogram(histogram)
        model.applyAutoWindow(.abdomen)

        let updatedPoints = model.currentControlPoints()
        XCTAssertGreaterThan(updatedPoints.count, AdvancedToneCurveModel.defaultControlPoints().count)

        // The autogenerated curve should focus around the populated bins (roughly 40...120).
        let shoulderPoint = updatedPoints.first { $0.x > 20 && $0.x < 150 }
        XCTAssertNotNil(shoulderPoint, "Auto window should introduce control points near the densest histogram region")
    }

    func testSampledValuesHonorCustomScale() {
        let model = AdvancedToneCurveModel(points: [
            .init(x: 0, y: 0),
            .init(x: 128, y: 0.25),
            .init(x: 255, y: 1)
        ])

        let lowResSamples = model.sampledValues(scale: 2)
        let highResSamples = model.sampledValues(scale: 8)

        XCTAssertEqual(lowResSamples.count, Int(255 * 2) + 1)
        XCTAssertEqual(highResSamples.count, Int(255 * 8) + 1)
        XCTAssertNotEqual(lowResSamples.count, highResSamples.count)
    }
}
